export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS= 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE';

export const FETCH_POST_UPDATE_REQUEST = 'FETCH_POST_UPDATE_REQUEST';
export const FETCH_POST_UPDATE_SUCCESS = 'FETCH_POST_UPDATE_SUCCESS';
export const FETCH_POST_UPDATE_FAILURE = 'FETCH_POST_UPDATE_FAILURE';

